export const products = [
  {
    id: 1,
    image: "",
    name: "Nombre del producto 1",
    category: "categoria del producto 1",
    description: "Descripcion del productos 1 adas a asdasda asda sdas dasd as d",
    price: 2540,
    stock: 10,
    initial: 1,
  },
  {
    id: 2,
    image: "",
    name: "Nombre del producto 2",
    category: "categoria del producto 2 ",
    description: "Descripcion del productos 2 adas a asdasda asda sdas dasd as d",
    price: 1500,
    stock: 12,
    initial: 1,
  },
  {
    id: 3,
    image: "",
    name: "Nombre del producto 3",
    category: "categoria del producto 3",
    description: "Descripcion del productos 3 adas a asdasda asda sdas dasd as d",
    price: 890,
    stock: 23,
    initial: 1,
  },
  {
    id: 4,
    image: "",
    name: "Nombre del producto 4",
    category: "categoria del producto 4",
    description: "Descripcion del productos 4 adas a asdasda asda sdas dasd as d",
    price: 3800,
    stock: 5,
    initial: 1,
  }
]